### ISSUE TITLE
clockwork repo

### ISSUE THREAD

**Issue by adamlangsner** [tomykaira/logres_hacks#1]
Hi @tomykaira 
I apologize for creating an issue on this repo but I'm not sure of another way to get in touch with you. I am interested in using the `clockwork` gem but I am getting a 404 when I go to https://github.com/tomykaira/clockwork
I see that the gem is published at rubygems but I was curious to know if the gem is being actively maintained or if there's another fork where it is being maintained. Thanks in advance and again I apologize for creating an issue on this unrelated repo.

**Comment by tomykaira** [comment]
Sorry, I am not sure why it is 404.
https://github.com/Rykian/clockwork is current repo.
